### ISSUE TITLE
from Proficy import iHistorian

### ISSUE THREAD

**Issue by mediero** [Top-Dog/GE-Proficy-Historian#1]
Hello,

I'm trying to run your code for export data from Historian to influxdb, please let me know how to implement the library  Proficy because the SDK is an com object "from Proficy import iHistorian".

Regards, Luis

**Comment by Top-Dog** [comment]
Hi, I'm not sure what your issue is? The provided code is the library code for Proficy, and iHistorian is just a class inside the module

**Comment by mediero** [comment]
You Are right the AV remove the files. Its ok
